const deliveryTimes = {
  AL: '1-3 days',
  AK: '',
  AZ: '3-5 days',
  AR: '1-3 days',
  CA: '3-5 days',
  CO: '3-5 days',
  CT: '3-5 days',
  DE: '1-3 days',
  FL: '1-3 days',
  GA: '1-3 days',
  HI: '',
  ID: '3-5 days',
  IL: '1-3 days',
  IN: '1-3 days',
  IA: '1-3 days',
  KS: '1-3 days',
  KY: '1-3 days',
  LA: '1-3 days',
  ME: '3-5 days',
  MD: '1-3 days',
  MA: '3-5 days',
  MI: '3-5 days',
  MN: '3-5 days',
  MS: '1-3 days',
  MO: '1-3 days',
  MT: '3-5 days',
  NE: '3-5 days',
  NV: '3-5 days',
  NH: '3-5 days',
  NJ: '1-3 days',
  NM: '3-5 days',
  NY: '3-5 days',
  NC: '1-3 days',
  ND: '3-5 days',
  OH: '1-3 days',
  OK: '1-3 days',
  OR: '3-5 days',
  PA: '3-5 days',
  RI: '3-5 days',
  SC: '1-3 days',
  SD: '3-5 days',
  TN: '1-3 days',
  TX: '1-3 days',
  UT: '3-5 days',
  VT: '3-5 days',
  VA: '1-3 days',
  WA: '3-5 days',
  WV: '1-3 days',
  WI: '3-5 days',
  WY: '3-5 days'
};

export default deliveryTimes;
